import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next_boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="/">Name</a>
        </h1>

        <p className={styles.description}>
          I am one-liner tagline/introduction{' '}
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a href="/." className={styles.card}>
            <h2>Some random thing &rarr;</h2>
            <p>grid 1</p>
          </a>

          <a href="./" className={styles.card}>
            <h2>some random thing &rarr;</h2>
            <p>grid 2</p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hello from Footer{' '}
          <span className={styles.logo}>
            <Image src="/" alt="Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
